name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.13.3", "2.12.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: keynmol/setup-scala@e63e2d9a3c6c13d7c37c5c1c1742e85736688c19
      - name: Test
        run: sbtn ++${{ matrix.scala }} ci
