name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        scala: ["2.13.3", "2.12.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: keynmol/setup-scala@v11
      - name: Test
        run: sbtn ++${{ matrix.scala }} ci
